### ISSUE TITLE
(Minor detail) Mistake in example command in assignment description

### ISSUE THREAD

**Issue by JeroenOudeVrielink** [SeyedHamidreza/cognitive_robotics_ws#7]
In part 1 of the assignment there is a number of example commands for VGG16:

$ roscore
$ rosrun rug_deep_feature_extraction multi_view_RGBD_object_representation.py vgg16_fc1
$ roslaunch rug_kfold_cross_validation kfold_cross_validation_RGBD_deep_learning_descriptor.launch **ortho**
base_network:=vgg16_fc1 K_for_KNN:=3 name_of_approach:=TEST

The **ortho** in bold should not be there.

**Comment by SeyedHamidreza** [comment]
updated!

**Comment by SeyedHamidreza** [comment]
updated!
